spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:moneyspread
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 3306