spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: dev

  datasource:
    data: classpath:import.sql
    url: jdbc:h2:mem:moneyspread
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true

server:
  port: 3306